modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/GenerationsMod"
license = "Insert License Here"

[[mods]]
modId = "generationsextra"
version = "${version}"
displayName = "Generations Extra"
authors = "The Generations Team"
description = '''
'''
#logoFile = ""

[[dependencies.generationsextra]]
modId = "forge"
mandatory = true
versionRange = "[47.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.generationsextra]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.generationsextra]]
modId = "generations_core"
mandatory = true
versionRange = "[4.1.1-Beta,)"
ordering = "BEFORE"
side = "BOTH"
